// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwxjW_UGQcOFCzvmXGHXmZTxaYhPkJyC8',
    appId: '1:238881511691:web:15d1aa2f6d5cb9df83aa0e',
    messagingSenderId: '238881511691',
    projectId: 'ecommerce-74462',
    authDomain: 'ecommerce-74462.firebaseapp.com',
    storageBucket: 'ecommerce-74462.firebasestorage.app',
    measurementId: 'G-1WLQ937SMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNb7zRfIz4WB7787gOKiQ3A0mvxjWVIbM',
    appId: '1:238881511691:android:beb9fa7b9d20b40b83aa0e',
    messagingSenderId: '238881511691',
    projectId: 'ecommerce-74462',
    storageBucket: 'ecommerce-74462.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0WBwjyKNRasdG26qEVJzOrSd_oSlKqJU',
    appId: '1:238881511691:ios:319f9dcd1fd222a883aa0e',
    messagingSenderId: '238881511691',
    projectId: 'ecommerce-74462',
    storageBucket: 'ecommerce-74462.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );
}
